//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leads_MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Звонки
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Звонки()
        {
            this.Лиды = new HashSet<Лиды>();
        }
    
        public int Индекс { get; set; }
        public System.DateTime Дата_время_звонка_по_лиду { get; set; }
        public int Длительность { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Лиды> Лиды { get; set; }
    }
}
