//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leads_MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Лиды
    {
        public int Индекс { get; set; }
        public string Номер_телефона_клиента { get; set; }
        public int Пользователь { get; set; }
        public decimal Работа_с_возражениями { get; set; }
        public decimal Овладение_навыками_продаж { get; set; }
        public decimal Знание_продуктов_компании { get; set; }
        public System.DateTime Дата_время_создания_лида { get; set; }
        public int Статус { get; set; }
        public Nullable<int> Звонок { get; set; }
    
        public virtual Звонки Звонки { get; set; }
        public virtual Пользователи Пользователи { get; set; }
        public virtual Статус_Лида Статус_Лида { get; set; }
    }
}
